service: thumbbuster

custom:
  UploadBucket:
    Ref: TBUploadBucket
  TransformBucket:
    Ref: TBTransformBucket

provider:
  name: aws
  stage: ${opt:stage, ''}
  runtime: nodejs12.x
  profile: serverless-admin
  region: us-east-2
  environment:
    TRANSFORM_BUCKET: thumbbuster-${opt:stage, ''}-transform-bucket
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        - "Fn::Join":
          - ""
          - - "arn:aws:s3:::"
            - Ref: TBUploadBucket
            - "*"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource:
        - "Fn::Join":
          - ""
          - - "arn:aws:s3:::"
            - Ref: TBTransformBucket
            - "*"

functions:
  upload:
    handler: handler.handleUpload
    events:
      - s3:
          bucket: thumbbuster-${opt:stage, ''}-upload-bucket
          event: s3:ObjectCreated:*
          existing: true

resources:
  Resources:
    TBUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: thumbbuster-${opt:stage, ''}-upload-bucket
        
    TBTransformBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: thumbbuster-${opt:stage, ''}-transform-bucket

plugins:
  - serverless-plugin-typescript
